export const GET_INPUT_VALUES = 'GET_INPUT_VALUES';
export const REQUEST_STARTS = 'REQUEST_STARTS';
export const GET_LOAN_INTREST = 'GET_LOAN_INTREST';
export const API_RESPONSE_MESSAGE = 'API_RESPONSE_MESSAGE';
export const PREFILL_INPUTS = 'PREFILL_INPUTS';
